name: value_notifier_plus
description: ValueNotifierPlus é um pacote que expande as funcionalidades de ValueNotifier do Flutter.
version: 0.1.0+10
repository: https://github.com/Flutterando/value_notifier_plus
topics:
  - reactive-programming
  - state-management
  - observables
  - reactive
  - bloc


environment:
  sdk: ">=2.12.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0
