name: value_notifier_plus
description: ValueNotifierPlus é um pacote que expande as funcionalidades de ValueNotifier do Flutter.
version: 0.1.0+7
repository: https://github.com/Flutterando/value_notifier_plus
topics:
  - reactive-programming
  - state-management
  - observables
  - reactive
  - bloc


environment:
  sdk: ^3.4.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0
